version: '3.1'
services:
  webdav-server:
    build: .
    ports:
      - '4443:443'
    volumes:
      - 'webdav-server:/var/webdav'
      - '/etc/ssl/certs/webdav-server.crt:/etc/ssl/certs/webdav-server.crt'
      - '/etc/ssl/private/webdav-server.key:/etc/ssl/private/webdav-server.key'
      - '/etc/ssl/webdav-server-diffie-hellman-ephemeral-parameters.pem:/etc/ssl/webdav-server-diffie-hellman-ephemeral-parameters.pem'
volumes:
  webdav-server:
